#ini file used for saving setting like :  -v -s saved here, everytime run take -v -s with command once saved in .ini file

#Dont need to give command -v -s everytime once saved here (Example: addopts = -v -s )
#path should be main project folderfolder

#We are telling ini file to accept smoke, regression markers so accept it without any error, else it will throw error in console to register the test

#pytest -m "smoke or regression"  # runs both   > in ini file we have to save in settings

[pytest]

;addopts = -v -s
;testpaths = Pytest/test_actions

markers = smoke : testcases
            regression : testcases
